### ISSUE TITLE
Deploy with docker compose

### ISSUE THREAD

**Issue by xyxc0673** [payloadcms/next-payload-demo#8]
Hi,

I am working with a next and payload app just like the repo. Now I want to deploy with docker in my server.

Here is docker-compose.yml
```yml
version: "3"
services:
  next-payload-demo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3600:3000"
    depends_on:
      - mongo
    environment:
       MONGODB_URI: mongodb://mongo:27017/next-payload-demo
    env_file:
      - .env
    networks:
      - app_network
    command: sh -c "echo $MONGODB_URI"

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=next-payload-demo
    env_file:
      - .env
    volumes:
      - mongodata:/data/db
    networks:
      - app_network

volumes:
  mongodata:

networks:
  app_network:
```

Here is Dockerfile
```yml
FROM node:18-alpine AS base

# Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
  else echo "Lockfile not found." && exit 1; \
  fi


# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
# ENV NEXT_TELEMETRY_DISABLED 1

RUN yarn build

# If using npm comment out above and use below instead
# RUN npm run build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV production
# Uncomment the following line in case you want to disable telemetry during runtime.
# ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000
# set hostname to localhost
ENV HOSTNAME "0.0.0.0"

CMD ["node", "server.js"]
```

However it gave me errors while I run `docker compose build`
```
=> ERROR [next-payload-demo2 builder 4/4] RUN yarn build                                                                                             37.6s 
------                                                                                                                                                      
 > [next-payload-demo2 builder 4/4] RUN yarn build:                                                                                                         
0.284 yarn run v1.22.19                                                                                                                                     
0.304 $ yarn build:next
0.459 $ next build
0.727 - info Loaded env from /app/.env
1.610 - warn You have enabled experimental feature (outputFileTracingExcludes) in next.config.js.
1.610 - warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
1.610 
1.622 Attention: Next.js now collects completely anonymous telemetry regarding usage.
1.622 This information is used to shape Next.js' roadmap and prioritize features.
1.622 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
1.622 https://nextjs.org/telemetry
1.622 
1.681 - info Creating an optimized production build...
37.22 Failed to compile.
37.22 
37.22 ./pages/api/[collection]/versions/[id].ts
37.22 Module not found: Can't resolve '@payloadcms/next-payload/dist/handlers/[collection]/versions/[id]'
37.22 
37.22 https://nextjs.org/docs/messages/module-not-found
37.22 
37.22 ./pages/api/[collection]/versions/index.ts
37.22 Module not found: Can't resolve '@payloadcms/next-payload/dist/handlers/[collection]/versions'
37.22 
37.22 https://nextjs.org/docs/messages/module-not-found
37.22 
37.22 ./pages/api/globals/[global]/versions/[id].ts
37.22 Module not found: Can't resolve '@payloadcms/next-payload/dist/handlers/globals/[global]/versions/[id]'
37.22 
37.22 https://nextjs.org/docs/messages/module-not-found
37.22 
37.22 ./pages/api/globals/[global]/versions/index.ts
37.22 Module not found: Can't resolve '@payloadcms/next-payload/dist/handlers/globals/[global]/versions'
37.22 
37.22 https://nextjs.org/docs/messages/module-not-found
37.22 
37.23 
37.23 > Build failed because of webpack errors
37.34 error Command failed with exit code 1.
37.34 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
37.36 error Command failed with exit code 1.
37.36 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1
```

I don't exactly know what's the issue.
Are my config files incorrect?
